[defaults]
ignore = "dirty"


[vendor-utils]
path = "vendor/utils"
url = "https://github.com/example/utils.git"
sparse_paths = ["src/", "include/", "*.md"]
ignore = "all" # override default ignore setting

[my-submodule]
path = "my-submodule"
url = "https://github.com/example/my-submodule.git"
sparse_paths = ["src/", "include/"]
ignore = "all"
