# SPDX-FileCopyrightText: 2025 Adam Poulemanos <89049923+bashandbone@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

tabWidth = 4
useTabs = false

[[overrides]]
files = ["*.json", "*.jsonc", "*.json5"]
tabWidth = 2
useTabs = false
parser = "json"
