[package]
name = "submod"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"
description = "Git submodule manager with sparse checkout support using gitoxide"
authors = ["Adam Poulemanos <89049923+bashandbone@users.noreply.github.com>"]
resolver = "3"

[dependencies]
# Gitoxide ops
gix = { version = "0.72.1", features = ["max-performance"] }
gix-config = { version = "0.45.1", features = ["serde"] }
gix-submodule = "0.19.1"
bstr = { version = "1.12.0", default-features = false }

# CLI
clap = { version = "4.5.40", features = ["derive"] }

# TOML config
toml = "0.8.23"
toml_edit = "0.22.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

# errors
anyhow = "1.0.98"
thiserror = "2.0.12"

# optional for better low-level ops; falls back to using `git` directly if not available
git2 = { version = "0.20.2", optional = true }


[[bin]]
name = "submod"
path = "src/main.rs"

[features]
default = ["git2-support"]
git2-support = ["git2"]

[dev-dependencies]
tempfile = "3.14.0"
serde_json = "1.0.140"
